#=========================== Filebeat inputs =============================

filebeat.inputs:

- type: log
  enabled: true
  encoding: utf-8
  fields:
    _zb_api: true
  fields_under_root: true

  paths:
    - /opt/webroot/recharge-api/log/info/*.log
    - /opt/webroot/recharge-api/log/error/*.log
    - /opt/webroot/recharge-api/log/warn/*.log

  scan_frequency: 1s
  exclude_lines: ['^------------', '^[[:space:]]*$']
  multiline.pattern: ^[-]{10,}
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  encoding: utf-8
  fields:
    _zb_customer: true
  fields_under_root: true

  scan_frequency: 1s
  paths:
    - /opt/webroot/recharge-customer/log/*/*.log
    
  exclude_lines: ['^------------', '^[[:space:]]*$']
  multiline.pattern: ^[-]{10,}
  multiline.negate: true
  multiline.match: after

#================================ General ======================================


#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

#============================== Kibana =====================================
setup.kibana:

# setup.ilm.enabled: false
#============================== Template =====================================

setup.template.enabled: true
setup.template.name: "zb_score"
setup.template.pattern: "zb_score-*"

setup.ilm:
  enabled: auto
  rollover_alias: "zb_score"
  pattern: "{now/d}-000001"

#================================ Outputs =====================================

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["elasticsearch:9200"]
  
  username: "elastic"
  password: "changeme"

  index: "zb_score-%{+yyyy.MM.dd}" 

#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
